version: '3'

services:

  mysql:
    image: rkrahl/mariadb
    volumes:
      - ./mysql/init:/etc/mysql.d:ro
      - db:/var/lib/mysql

  build:
    build:
      context: ./build/image
    depends_on:
      - mysql
    volumes:
      - ./build/my.cnf:/home/abuild/.my.cnf:ro
      - ./build/apps:/home/abuild/apps
      - ./build/src:/home/abuild/src
      - gfdomain:/home/abuild/payara6/glassfish/domains


volumes:
  db:
  gfdomain:
