version: '3'

services:

  mysql:
    image: rkrahl/mariadb
    volumes:
      - ./mysql/init:/etc/mysql.d:ro
      - db:/var/lib/mysql

  build:
    build:
      context: ./build/image
    depends_on:
      - mysql
    volumes:
      - $BUILDHOME:/home/abuild
      - ./build/apps:/home/abuild/apps
      - ./build/src:/home/abuild/src
      - ./build/certs:${GLASSFISH_HOME}/certs
      - $SSH_AUTH_DIR:$SSH_AUTH_DIR
      - gfdomain:${GLASSFISH_HOME}/glassfish/domains
    environment:
      SSH_AUTH_SOCK:


volumes:
  db:
  gfdomain:
